memory_limit = 256M
upload_max_filesize = 12M
post_max_size = 16M
max_execution_time = 60
date.timezone = America/Bogota
expose_php = Off

opcache.enable = 1
opcache.memory_consumption = 96
opcache.max_accelerated_files = 8000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

session.cookie_httponly = 1
session.use_strict_mode = 1
